### PR TITLE
Upgrade nix dependency to 0.26.1, limit features

### PR DESCRIPTION
**Pull request by rtzoeller**

### CODE REVIEW

**Comment by rtzoeller** [comment]
Supersedes #5

**Review by passcod — APPROVED** [review]

**Comment by rtzoeller** [comment]
Looks like a miss on my part - that module isn't used on Linux. Will fix.

**Comment by rtzoeller** [comment]
@passcod can we try again?

**Comment by passcod** [comment]
bors retry

**Comment by rtzoeller** [comment]
> Build failed:
> 
>     * [Test on macos with Rust 1.51.0 (feat: default)](https://github.com/watchexec/command-group/actions/runs/3606837968/jobs/6078457901)

That error doesn't look particularly related to my changes, and I'm a bit skeptical. @passcod any ideas?

**Comment by passcod** [comment]
hmm I'll run a try from unmodified code in #9, see if that appears

**Comment by passcod** [comment]
Looks like it's specifically on 1.51. I might just bump this crate's msrv; I'll figure out an appropriate one later today

**Comment by rtzoeller** [comment]
> Looks like it's specifically on 1.51. I might just bump this crate's msrv; I'll figure out an appropriate one later today

No real preference from me, but if you end up at 1.56 or higher let me know and I will update this PR to target nix 0.26. I'm fine leaving it at 0.25 though, if you prefer an older MSRV.

**Comment by passcod** [comment]
Yeah I'm going with 1.60

**Pull request merged**
